language: ruby
install: bundle install
cache:
  directories:
  - fftw/bundle
env:
  - CPLUS_INCLUDE_PATH=/usr/include:/usr/include/atlas C_INCLUDE_PATH=/usr/include:/usr/include/atlas
bundler_args: --without :development
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
  - "2.1.2"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfftw3-dev libatlas-base-dev
script: CODECLIMATE_REPO_TOKEN=ce953eb332bfdfbdad4a2e10d5764a334edff4eea7ef888786d9575b1bbec012 bundle exec rake compile && bundle exec rake spec
